spring:
  application:
    name: AdvancedHospitalManagementSystem


  datasource:
    url: jdbc:mysql://localhost:3306/hospital_management
    username: root
    password: HOSPITAL@1256

    openai:
      api:
        key: $(OPENAI_API_KEY)
        model: gpt-5.6-luna


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true